# Generated by Django 3.1.7 on 2021-03-03 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название поля')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('square', models.PositiveIntegerField(verbose_name='Площадь поля')),
                ('coordinate', models.CharField(max_length=128, verbose_name='Координаты поля')),
                ('cadastral_number', models.CharField(max_length=64, verbose_name='Кадастровый номер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_fields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_harvest', models.IntegerField(verbose_name='Планируемый урожай')),
                ('actual_harvest', models.IntegerField(verbose_name='Фактический урожай')),
                ('sowing_date', models.DateField(verbose_name='Дата сева')),
                ('harvest_date', models.DateField(verbose_name='Дата сбора')),
                ('density', models.CharField(max_length=32, verbose_name='Плотность засева')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='fields.culture')),
                ('field', models.ManyToManyField(related_name='crop_fields', to='fields.Field', verbose_name='поле')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='fields.season')),
            ],
        ),
    ]
