# Generated by Django 3.1.7 on 2021-03-03 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0003_auto_20210303_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='field',
        ),
        migrations.AddField(
            model_name='crop',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='fields.field'),
            preserve_default=False,
        ),
    ]
