# Generated by Django 3.1.7 on 2021-03-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCulture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='Название культуры')),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Тип культуры',
                'verbose_name_plural': 'Типы культур',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ChemicalElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=64, verbose_name='Название элемента')),
                ('abbreviation', models.CharField(max_length=12, verbose_name='Аббревиатура элемента')),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Химический элемент',
                'verbose_name_plural': 'Химические элементы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Название удобрения')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('units', models.CharField(choices=[('кг', 'килограмм'), ('т', 'тонн'), ('г', 'грамм')], max_length=64)),
                ('color', models.CharField(choices=[('Нет', 'Не окрашенный'), ('Да', 'Окрашенный')], max_length=64)),
                ('description', models.TextField()),
                ('advantages', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('post', models.BooleanField(default=False)),
                ('compositions', models.ManyToManyField(related_name='fertilizer_compositions', to='handbook.ChemicalElement', verbose_name='Химический элемент')),
                ('culture', models.ManyToManyField(related_name='fertilizer_cultures', to='handbook.CategoryCulture', verbose_name='Культура')),
            ],
            options={
                'verbose_name': 'Удобрение',
                'verbose_name_plural': 'Удобрения',
                'ordering': ('name',),
            },
        ),
    ]
