# Generated by Django 3.1.7 on 2021-03-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizer',
            name='color',
            field=models.CharField(choices=[('Не окрашенный', 'Нет'), ('Окрашенный', 'Да')], max_length=64),
        ),
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, verbose_name='Название вредителя')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='pests/')),
                ('phase', models.CharField(max_length=128, verbose_name='Фаза развития')),
                ('organ', models.CharField(max_length=128, verbose_name='Поражаемые органы')),
                ('description', models.TextField()),
                ('region', models.TextField(verbose_name='Регион распространения')),
                ('culture', models.ManyToManyField(related_name='pest_cultures', to='handbook.CategoryCulture', verbose_name='Культура')),
            ],
            options={
                'verbose_name': 'Вредитель',
                'verbose_name_plural': 'Вредители',
                'ordering': ('name',),
            },
        ),
    ]
